@startuml "FaitChier"
skinparam linetype polyline
skinparam linetype ortho



rectangle rencontre{
    class match{
    }

    class equipe{
        -nomDeEquipe
        -nombreJoueur
    }

    class joueur{
        -nom 
        -classement
        -capitaine
    }

}
rectangle arbitre{

    class arbitre{

    }

    

    class set{

        +services
    }

}

rectangle classement{

    class score{
    }

    class classement{
    }

    class historique{
    }
}



arbitre --[#1117e6]> match
match --> set 

match --> equipe 
equipe --> joueur


score --> historique
set <-- classement 
set <-- score





@enduml